name: gpt
params:
  block_size: 512
  num_layers: 10
  embed_dim: 512
  num_heads: 8
  attn_bias: False
  linear_expansion_factor: 4
  activation: gelu
  dropout: 0.3
# checkpoint:
#   path:
#   file:

