defaults:
  - data: dr_seuss
  - model: gpt
  - loss: cross_entropy
  - optimizer: adamw
  - scheduler: onecycle
  - logging: logging

project_name: SeussGPT
experiment_name: ${now:%Y-%m-%d_%H:%M:%S}_${project_name}_${model.name}_${data.dataset_name}_${loss.name}_${optimizer.name}_${scheduler.name}

block_size: ${model.params.block_size}
batch_size: ${data.batch_size}

num_epochs: 5000
seed: 1001001

